<a href="https://colab.research.google.com/github/justgoforit1973/data-analysis-basic-kadai/blob/main/kadai_003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

array_a = np.random.randint(1,99,(4,2))
print(array_a)

array_b = np.array([[1,2,3,4],[4,5,6,4]])
print(array_b)

multiple_array = np.dot(array_a, array_b)
print(multiple_array)

print(multiple_array.max())







[[67 66]
 [30 98]
 [49 38]
 [60 31]]
[[1 2 3 4]
 [4 5 6 4]]
[[331 464 597 532]
 [422 550 678 512]
 [201 288 375 348]
 [184 275 366 364]]
678
